// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im_msg.proto

/*
Package im is a generated protocol buffer package.

It is generated from these files:
	im_msg.proto

It has these top-level messages:
	Msg
*/
package im

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	FromUser string `protobuf:"bytes,1,opt,name=FromUser" json:"FromUser,omitempty"`
	ToUser   string `protobuf:"bytes,2,opt,name=ToUser" json:"ToUser,omitempty"`
	Data     string `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	Stamp    int64  `protobuf:"varint,4,opt,name=Stamp" json:"Stamp,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Msg) GetFromUser() string {
	if m != nil {
		return m.FromUser
	}
	return ""
}

func (m *Msg) GetToUser() string {
	if m != nil {
		return m.ToUser
	}
	return ""
}

func (m *Msg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Msg) GetStamp() int64 {
	if m != nil {
		return m.Stamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg)(nil), "im.msg")
}

func init() { proto.RegisterFile("im_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcc, 0x8d, 0xcf,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xcc, 0x55, 0x4a, 0xe6, 0x62,
	0xce, 0x2d, 0x4e, 0x17, 0x92, 0xe2, 0xe2, 0x70, 0x2b, 0xca, 0xcf, 0x0d, 0x2d, 0x4e, 0x2d, 0x92,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0xf2, 0xc1, 0x32,
	0x4c, 0x60, 0x19, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0xc5, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x19, 0x2c,
	0x0a, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0x06, 0x97, 0x24, 0xe6, 0x16, 0x48, 0xb0, 0x28, 0x30, 0x6a,
	0x30, 0x07, 0x41, 0x38, 0x49, 0x6c, 0x60, 0xfb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0xc7, 0xa4, 0x9c, 0x7f, 0x00, 0x00, 0x00,
}
